# -*- coding: utf-8 -*-
"""LayoutDM (iter1 blueprint).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CvUZ2JFe0O-prwKF0kif9xrpb6ypcM1
"""

# ==============================
# LayoutDM minimal - Colab script
# ==============================
# Paste this into a single Colab cell (or split as you like).
# It is written for correctness & clarity, not speed.

import math
from dataclasses import dataclass
from typing import Dict, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader


# ------------------------------
# 0) Config
# ------------------------------
@dataclass
class TrainConfig:
    # Diffusion
    T: int = 100                  # paper uses T=100
    lambda_aux: float = 0.1       # paper Eq.(4): λ=0.1

    # Optim (paper)
    lr: float = 5e-4
    beta1: float = 0.9
    beta2: float = 0.98
    weight_decay: float = 0.01

    # Transformer backbone (paper)
    n_layers: int = 4
    n_heads: int = 8
    d_model: int = 512
    d_ff: int = 2048
    dropout: float = 0.1

    # Layout shape
    M: int = 25                   # must match your tokenization pipeline
    device: str = "cuda" if torch.cuda.is_available() else "cpu"


# ------------------------------
# 1) Dataset (tokens already discrete)
# ------------------------------
class LayoutTokenDataset(Dataset):
    """
    Each item:
      tokens:   LongTensor [M, 5]  (c,x,y,w,h) already discrete + padded
      pad_mask: BoolTensor [M, 5]  True where token == PAD
    """
    def __init__(self, token_tensors: torch.LongTensor, pad_token_id: int):
        self.x = token_tensors
        self.pad_id = pad_token_id

    def __len__(self):
        return self.x.size(0)

    def __getitem__(self, idx):
        tokens = self.x[idx]
        pad_mask = (tokens == self.pad_id)
        return tokens, pad_mask


def load_or_make_dataset(cfg: TrainConfig, vocab_meta: Dict[str, Dict[str, int]]) -> Tuple[Dataset, Dataset]:
    """
    Dummy dataset so the notebook runs.
    Replace this with real tokenized RICO / PubLayNet:
      - tokens are already KMeans-quantized for x,y,w,h
      - padded to M
      - include [MASK] and [PAD] in each modality vocab
    """
    torch.manual_seed(0)

    N_train = 512
    N_val = 128
    M = cfg.M

    # We'll build random tokens in a safe range (not using MASK/PAD)
    # For demo only.
    def make_split(N):
        split = torch.zeros((N, M, 5), dtype=torch.long)
        for a, m in enumerate(["c", "x", "y", "w", "h"]):
            V = vocab_meta[m]["vocab_size"]
            mask_id = vocab_meta[m]["mask_id"]
            pad_id = vocab_meta[m]["pad_id"]

            # sample from [0..V-1] excluding mask/pad (demo)
            choices = [i for i in range(V) if i not in (mask_id, pad_id)]
            split[:, :, a] = torch.tensor(
                torch.randint(0, len(choices), (N, M)),
                dtype=torch.long
            )
            split[:, :, a] = torch.take(torch.tensor(choices), split[:, :, a])

        # simulate variable length: last 5 slots are PAD
        pad_id_c = vocab_meta["c"]["pad_id"]
        split[:, -5:, :] = pad_id_c
        return split

    train_tokens = make_split(N_train)
    val_tokens = make_split(N_val)

    pad_id = vocab_meta["c"]["pad_id"]
    return LayoutTokenDataset(train_tokens, pad_id), LayoutTokenDataset(val_tokens, pad_id)


# ------------------------------
# 2) Diffusion: transition params and Qt
# ------------------------------
def make_transition_params(t: int, T: int) -> Tuple[float, float, float]:
    """
    Returns (alpha_t, beta_t, gamma_t).
    IMPORTANT: To replicate the paper strictly, replace this schedule
    with the exact schedule from the paper.
    """
    # Placeholder schedule (works, but not guaranteed paper-exact):
    s = (t / T)
    gamma_t = math.sin(s * math.pi / 2) ** 2      # 0..1 increasing
    beta_t = 0.01 * (1.0 - gamma_t)               # small
    alpha_t = 1.0 - gamma_t                       # base (we'll renormalize rows)
    return alpha_t, beta_t, gamma_t


def build_Qt(V: int, alpha_t: float, beta_t: float, gamma_t: float,
             mask_id: int, device: torch.device) -> torch.Tensor:
    """
    Build Qt [V,V] for D3PM-style masking diffusion.

    For normal tokens i != mask:
      - stay on i: alpha + beta
      - replace to any other normal token: beta
      - go to MASK: gamma
      Row is renormalized.

    MASK is absorbing:
      Qt[mask, mask] = 1
    """
    Qt = torch.zeros((V, V), device=device, dtype=torch.float32)

    normal_ids = [i for i in range(V) if i != mask_id]

    for i in normal_ids:
        Qt[i, i] = alpha_t + beta_t
        for j in normal_ids:
            if j != i:
                Qt[i, j] = beta_t
        Qt[i, mask_id] = gamma_t

        Qt[i] = Qt[i] / (Qt[i].sum() + 1e-12)

    Qt[mask_id, :] = 0.0
    Qt[mask_id, mask_id] = 1.0
    return Qt


@torch.no_grad()
def categorical_sample(probs: torch.Tensor) -> torch.Tensor:
    """
    probs: [..., V] categorical distributions
    returns: [...] int64 sample
    """
    flat = probs.reshape(-1, probs.size(-1))
    out = torch.multinomial(flat, num_samples=1).squeeze(-1)
    return out.view(probs.shape[:-1])


def q_sample_from_Qbar(z0: torch.Tensor, Qbar_t: torch.Tensor) -> torch.Tensor:
    """
    z0: [B, L] tokens
    Qbar_t: [V, V]
    sample zt ~ q(zt|z0)
    """
    probs = Qbar_t[z0]  # [B, L, V]
    return categorical_sample(probs)


def q_posterior_true(z0: torch.Tensor, zt: torch.Tensor,
                     Qt: torch.Tensor, Qbar_t_1: torch.Tensor) -> torch.Tensor:
    """
    True posterior:
      q(z_{t-1} | z_t, z0) ∝ q(z_t | z_{t-1}) * q(z_{t-1} | z0)

    Returns [B, L, V]
    """
    probs_t1_given_z0 = Qbar_t_1[z0]  # [B, L, V]
    Qt_col = Qt[:, zt].permute(1, 2, 0).contiguous()  # [B, L, V]
    unnorm = Qt_col * probs_t1_given_z0
    return unnorm / (unnorm.sum(dim=-1, keepdim=True) + 1e-12)


# ------------------------------
# 3) Model: Transformer encoder denoiser
# ------------------------------
class LayoutDMDenoiser(nn.Module):
    def __init__(self, cfg: TrainConfig, vocab_sizes: Dict[str, int]):
        super().__init__()
        self.cfg = cfg
        self.modalities = ["c", "x", "y", "w", "h"]

        self.emb = nn.ModuleDict({
            m: nn.Embedding(vocab_sizes[m], cfg.d_model) for m in self.modalities
        })

        # Decoupled positional embeddings:
        self.elem_pos = nn.Embedding(cfg.M, cfg.d_model)  # element index 0..M-1
        self.attr_pos = nn.Embedding(5, cfg.d_model)      # attribute index 0..4

        enc_layer = nn.TransformerEncoderLayer(
            d_model=cfg.d_model,
            nhead=cfg.n_heads,
            dim_feedforward=cfg.d_ff,
            dropout=cfg.dropout,
            batch_first=True,
            activation="gelu",
            norm_first=True,
        )
        self.encoder = nn.TransformerEncoder(enc_layer, num_layers=cfg.n_layers)

        self.head = nn.ModuleDict({
            m: nn.Linear(cfg.d_model, vocab_sizes[m]) for m in self.modalities
        })

    def forward(self, zt: torch.Tensor) -> Dict[str, torch.Tensor]:
        """
        zt: [B, M, 5]
        Return logits per modality: m -> [B, M, V_m]
        """
        B, M, A = zt.shape
        assert M == self.cfg.M and A == 5

        elem_ids = torch.arange(M, device=zt.device).unsqueeze(0).expand(B, M)  # [B,M]

        reps = []
        for a, m in enumerate(self.modalities):
            tok = zt[:, :, a]                           # [B,M]
            e = self.emb[m](tok)                        # [B,M,d]
            e = e + self.elem_pos(elem_ids) + self.attr_pos(torch.full((B, M), a, device=zt.device, dtype=torch.long))
            reps.append(e)

        # flatten attributes as sequence length M*5
        x = torch.cat(reps, dim=1)                      # [B, M*5, d]
        h = self.encoder(x)                             # [B, M*5, d]

        out = {}
        offset = 0
        for a, m in enumerate(self.modalities):
            hm = h[:, offset:offset + M, :]             # [B,M,d]
            out[m] = self.head[m](hm)                   # [B,M,V]
            offset += M
        return out


# ------------------------------
# 4) Losses: VB (KL) + aux (CE on z0)
# ------------------------------
def kl_categorical(p: torch.Tensor, q: torch.Tensor) -> torch.Tensor:
    return (p * (torch.log(p + 1e-12) - torch.log(q + 1e-12))).sum(dim=-1)


def compute_losses(
    cfg: TrainConfig,
    logits: Dict[str, torch.Tensor],  # m -> [B,M,V]
    z0: torch.Tensor,                 # [B,M,5]
    zt: torch.Tensor,                 # [B,M,5]
    t: int,
    Qts_t: Dict[str, torch.Tensor],          # m -> Qt [V,V]
    Qbars_prev: Dict[str, torch.Tensor],     # m -> Qbar_{t-1} [V,V]
    pad_mask: torch.Tensor,                  # [B,M,5] bool
) -> Tuple[torch.Tensor, Dict[str, float]]:
    modalities = ["c", "x", "y", "w", "h"]
    vb_terms, aux_terms = [], []

    B, M, _ = z0.shape

    for a, m in enumerate(modalities):
        V = logits[m].size(-1)
        z0_m = z0[:, :, a]              # [B,M]
        zt_m = zt[:, :, a]              # [B,M]

        valid = (~pad_mask[:, :, a]).float()  # [B,M]
        denom = valid.sum().clamp_min(1.0)

        # true posterior q(z_{t-1} | z_t, z0)
        q_true = q_posterior_true(z0_m, zt_m, Qts_t[m], Qbars_prev[m])  # [B,M,V]

        # model posterior p_theta(z_{t-1} | z_t)
        p_model = F.softmax(logits[m], dim=-1)

        # VB
        kl = kl_categorical(q_true, p_model)          # [B,M]
        vb = (kl * valid).sum() / denom
        vb_terms.append(vb)

        # Aux: CE to reconstruct z0
        ce = F.cross_entropy(logits[m].reshape(-1, V), z0_m.reshape(-1), reduction="none").reshape(B, M)
        aux = (ce * valid).sum() / denom
        aux_terms.append(aux)

    vb_loss = torch.stack(vb_terms).mean()
    aux_loss = torch.stack(aux_terms).mean()
    total = vb_loss + cfg.lambda_aux * aux_loss

    return total, {
        "loss_total": float(total.detach().cpu()),
        "loss_vb": float(vb_loss.detach().cpu()),
        "loss_aux": float(aux_loss.detach().cpu()),
    }


# ------------------------------
# 5) Training loop (minimal, clear)
# ------------------------------
def precompute_Q_mats(cfg: TrainConfig, vocab_meta: Dict[str, Dict[str, int]], device: torch.device):
    """
    Precompute Qt[t] and Qbar[t] for each modality, for t=0..T.
    """
    Qts_all = {m: {} for m in vocab_meta}
    Qbars_all = {m: {} for m in vocab_meta}

    for m, meta in vocab_meta.items():
        V = meta["vocab_size"]
        mask_id = meta["mask_id"]

        Qbar = torch.eye(V, device=device)
        Qbars_all[m][0] = Qbar.clone()

        for t in range(1, cfg.T + 1):
            alpha_t, beta_t, gamma_t = make_transition_params(t, cfg.T)
            Qt = build_Qt(V, alpha_t, beta_t, gamma_t, mask_id, device)
            Qts_all[m][t] = Qt

            Qbar = Qt @ Qbar
            Qbars_all[m][t] = Qbar.clone()

    return Qts_all, Qbars_all


def train_one_epoch(cfg: TrainConfig, model: nn.Module, loader: DataLoader,
                    opt: torch.optim.Optimizer, Qts_all, Qbars_all,
                    vocab_meta: Dict[str, Dict[str, int]]):
    model.train()
    device = torch.device(cfg.device)

    step = 0
    for tokens, pad_mask in loader:
        tokens = tokens.to(device)        # [B,M,5]
        pad_mask = pad_mask.to(device)    # [B,M,5]
        B = tokens.size(0)

        # sample a single timestep for the batch (common diffusion practice)
        t = torch.randint(1, cfg.T + 1, (1,), device=device).item()

        # build zt by modality from Qbar_t
        zt = tokens.clone()
        Qts_t = {}
        Qbars_prev = {}

        for a, m in enumerate(["c", "x", "y", "w", "h"]):
            Qbar_t = Qbars_all[m][t]
            zt[:, :, a] = q_sample_from_Qbar(tokens[:, :, a], Qbar_t)

            Qts_t[m] = Qts_all[m][t]
            Qbars_prev[m] = Qbars_all[m][t - 1]

        logits = model(zt)

        loss, metrics = compute_losses(cfg, logits, tokens, zt, t, Qts_t, Qbars_prev, pad_mask)

        opt.zero_grad(set_to_none=True)
        loss.backward()
        opt.step()

        step += 1
        if step % 50 == 0:
            print(f"step={step:04d} t={t:03d} "
                  f"loss={metrics['loss_total']:.4f} vb={metrics['loss_vb']:.4f} aux={metrics['loss_aux']:.4f}")


# ------------------------------
# 6) Unconditional sampling (reverse diffusion)
# ------------------------------
@torch.no_grad()
def unconditional_sample(model: nn.Module, cfg: TrainConfig,
                         vocab_meta: Dict[str, Dict[str, int]],
                         batch_size: int = 4) -> torch.LongTensor:
    """
    z_T: all [MASK] for all modalities
    for t=T..1:
      logits = model(z_t) -> p(z_{t-1}|z_t)
      sample categorical -> z_{t-1}
    """
    model.eval()
    device = torch.device(cfg.device)

    modalities = ["c", "x", "y", "w", "h"]
    mask_ids = {m: vocab_meta[m]["mask_id"] for m in modalities}
    pad_ids  = {m: vocab_meta[m]["pad_id"]  for m in modalities}

    B, M = batch_size, cfg.M

    # init z_T
    zt = torch.zeros((B, M, 5), dtype=torch.long, device=device)
    for a, m in enumerate(modalities):
        zt[:, :, a] = mask_ids[m]

    for t in range(cfg.T, 0, -1):
        logits = model(zt)  # m -> [B,M,V]
        z_prev = zt.clone()

        for a, m in enumerate(modalities):
            probs = F.softmax(logits[m], dim=-1)  # [B,M,V]
            flat = probs.reshape(-1, probs.size(-1))
            sampled = torch.multinomial(flat, 1).squeeze(-1).view(B, M)
            z_prev[:, :, a] = sampled

        # coherence rule for PAD:
        # if category is PAD in a slot, force x,y,w,h to PAD too
        c_pad = (z_prev[:, :, 0] == pad_ids["c"])
        if c_pad.any():
            z_prev[:, :, 1] = torch.where(c_pad, torch.full_like(z_prev[:, :, 1], pad_ids["x"]), z_prev[:, :, 1])
            z_prev[:, :, 2] = torch.where(c_pad, torch.full_like(z_prev[:, :, 2], pad_ids["y"]), z_prev[:, :, 2])
            z_prev[:, :, 3] = torch.where(c_pad, torch.full_like(z_prev[:, :, 3], pad_ids["w"]), z_prev[:, :, 3])
            z_prev[:, :, 4] = torch.where(c_pad, torch.full_like(z_prev[:, :, 4], pad_ids["h"]), z_prev[:, :, 4])

        zt = z_prev

    return zt  # z_0


# ------------------------------
# 7) Main: wire everything
# ------------------------------
def main():
    cfg = TrainConfig(M=25)
    print("Device:", cfg.device)

    # You MUST align these IDs with your tokenization.
    # Each modality vocab includes:
    #   normal tokens + [MASK] + [PAD]
    vocab_meta = {
        "c": {"vocab_size": 30, "mask_id": 28, "pad_id": 29},  # example only
        "x": {"vocab_size": 66, "mask_id": 64, "pad_id": 65},  # example only
        "y": {"vocab_size": 66, "mask_id": 64, "pad_id": 65},
        "w": {"vocab_size": 66, "mask_id": 64, "pad_id": 65},
        "h": {"vocab_size": 66, "mask_id": 64, "pad_id": 65},
    }
    vocab_sizes = {m: meta["vocab_size"] for m, meta in vocab_meta.items()}

    # Data
    train_ds, val_ds = load_or_make_dataset(cfg, vocab_meta)
    train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, drop_last=True)
    val_loader = DataLoader(val_ds, batch_size=16, shuffle=False, drop_last=False)

    # Model
    model = LayoutDMDenoiser(cfg, vocab_sizes).to(cfg.device)
    opt = torch.optim.AdamW(model.parameters(), lr=cfg.lr, betas=(cfg.beta1, cfg.beta2), weight_decay=cfg.weight_decay)

    # Precompute diffusion matrices
    device = torch.device(cfg.device)
    Qts_all, Qbars_all = precompute_Q_mats(cfg, vocab_meta, device)

    # Train (paper: 50 epochs for RICO, 20 for PubLayNet)
    epochs = 1
    for ep in range(epochs):
        print(f"\n=== Epoch {ep+1}/{epochs} ===")
        train_one_epoch(cfg, model, train_loader, opt, Qts_all, Qbars_all, vocab_meta)

    # Save checkpoint
    ckpt_path = "layoutdm_minimal.pt"
    torch.save({
        "cfg": cfg.__dict__,
        "model_state": model.state_dict(),
        "vocab_meta": vocab_meta,
    }, ckpt_path)
    print("Saved:", ckpt_path)

    # Unconditional sampling demo
    samples = unconditional_sample(model, cfg, vocab_meta, batch_size=4)
    print("Sample tokens shape:", samples.shape)  # [B,M,5]
    print("First sample (first 5 elements):\n", samples[0, :5, :])

main()

